// Generated by CoffeeScript 1.6.2
(function() {
  var Background, Twitter, TwitterCommands, exports, _ref,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Background = (function() {
    Background.prototype.commands = {
      'twitter': null
    };

    function Background(twitterCommands) {
      this.commands.twitter = twitterCommands;
      this.addEventListeners();
    }

    Background.prototype.addEventListeners = function() {
      var _this = this;

      chrome.extension.onRequest.addListener(function(message, sender, sendResponse) {
        var args, res, target;

        target = _this.commands[message.target];
        if (!target) {
          throw new Error("Invalid target " + message.target, _this.commands);
        }
        args = message.args;
        args.push(sendResponse);
        res = target[message.action].apply(target, args);
        if (res) {
          return sendResponse({
            res: res
          });
        }
      });
    };

    return Background;

  })();

  TwitterCommands = (function() {
    function TwitterCommands() {}

    TwitterCommands.prototype.sendSignedRequest = function(url, request, sendResponse) {
      var tw;

      tw = new Twitter(sendResponse);
      tw.sendSignedRequest(url, request);
    };

    return TwitterCommands;

  })();

  Twitter = (function() {
    Twitter.prototype._oauth = null;

    Twitter.prototype._authorizedCallback = null;

    function Twitter(_sendResponse) {
      this._sendResponse = _sendResponse;
      this._onSendSignedRequest = __bind(this._onSendSignedRequest, this);
      this._onAuthorized = __bind(this._onAuthorized, this);
    }

    Twitter.prototype._authorize = function() {
      console.log('Run authorizing.');
      this._oauth = ChromeExOAuth.initBackgroundPage({
        request_url: 'https://api.twitter.com/oauth/request_token',
        authorize_url: 'https://api.twitter.com/oauth/authorize',
        access_url: 'https://api.twitter.com/oauth/access_token',
        consumer_key: 'I7GcKlS4hnVloq9vLyvfQ',
        consumer_secret: 'N0eoeNkSufsKsnpywjKZsZeK6DrqA7Jhr7kW6I',
        scope: 'https://api.twitter.com/1.1/',
        app_name: 'vimmers_folow_status'
      });
      this._oauth.authorize(this._onAuthorized);
    };

    Twitter.prototype._onAuthorized = function() {
      var _ref;

      console.log('Authorized successfully.');
      if ((_ref = this._authorizedCallback) != null) {
        _ref.call(this);
      }
      this._authorizedCallback = null;
    };

    Twitter.prototype.sendSignedRequest = function(url, request) {
      var _this = this;

      this._authorizedCallback = function() {
        console.log('Call onAuthoried callback', url, request);
        _this._oauth.sendSignedRequest(url, _this._onSendSignedRequest, request);
        url = null;
        request = null;
      };
      this._authorize();
    };

    Twitter.prototype._onSendSignedRequest = function(response, xhr) {
      var resJson, _ref;

      resJson = JSON.parse(response);
      console.log('Response of sendSignedRequest', resJson);
      if (((_ref = resJson.errors) != null ? _ref[0].code : void 0) === 89) {
        this._removeOauthToken();
        console.log(localStorage);
        resJson = null;
      }
      this._sendResponse({
        res: resJson
      });
    };

    Twitter.prototype._removeOauthToken = function() {
      console.log('Remove oath access token.');
      localStorage.removeItem('oauth_tokenhttps://api.twitter.com/1.1/');
      localStorage.removeItem('oauth_token_secrethttps://api.twitter.com/1.1/');
    };

    return Twitter;

  })();

  exports = (_ref = exports != null ? exports : window) != null ? _ref : this;

  exports.bg = new Background(new TwitterCommands);

}).call(this);
